In [1]:
# Problem 1
import numpy as np
def mat_mult():
    A1 = [3, -1, 4]
    A2 = [1, 5, -9]
    A = np.array([A1,A2])
    B1 = [2, 6,-5, 3]
    B2 = [5, -8,9, 7]
    B3 = [9, -3,-2,-3]
    B = np.array([B1, B2, B3])
    return A@B

mat_mult()


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [2]:
# Problem 2
def cayley():
    A1 = [3, 1, 4]
    A2 = [1, 5, 9]
    A3 = [-5, 3, 1]
    A = np.array([A1,A2,A3])
    return -1*((A@A)@A) + 9*(A@A) - 15*(A)

cayley()


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
#problem 3
def mat_create():
    A = np.triu(np.ones(7))
    B = 5*np.triu(np.ones(7)) -1 *np.tril(np.ones(7)) -5*np.eye(7)
    C= A@B@A
    return C.astype(np.int64)
mat_create()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]], dtype=int64)

In [5]:
#problem 4

A= np.array([-3,7,9,-1,10,-1,-11])
def fancy_index(A):
    A[A<0] =0
    return A

fancy_index(A)

array([ 0,  7,  9,  0, 10,  0,  0])

In [6]:
#problem 5
def mat_stack():
    A = np.array([[0,2,4],[1,3,5]])
    B = np.tril(3*np.ones(3))
    C = -2*np.eye(3)
    z1 = np.zeros((3,3))
    z2 = np.zeros((2,2))
    z3 = np.zeros((2,3))
    z4 = np.zeros((3,2))
    st1 = np.hstack((z1,A.T,np.eye(3)))
    st2 = np.hstack((A,z2,z3))
    st3 =  np.hstack((B,z4,C))
    st = np.vstack((st1,st2,st3))
    return st

mat_stack()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

In [8]:
#problem 6
A = np.arange(16).reshape((4,4))
def row_stoch(A):
    row_sum = A.sum(axis=1)
    A_mark =  A.T/row_sum
    return A_mark.T


row_stoch(A)


array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778]])

Problem 7

In [4]:
# problem 7
def grid_max():
grid = np.load( "C:/Users/ministry of finance/Google Drive/OSM Bootcamp 2018/BootCamp2018/Computation/Wk1_PyIntro/grid.npy")
np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
max = 0
for i in range(20):
    for j in range(16):
        mult = grid[i,j]*grid[i,j+1]*grid[i,j+2]*grid[i,j+3]
        if mult>max:max = mult
        mult =  grid[j,i]*grid[j+1,i]*grid[j+2,i]*grid[j+3,i]
        if mult>max: max = mult

for i in range(16):
    for j in range(16):
        mult = grid[i,j]*grid[i+1,j+1]*grid[i+2,j+2]*grid[i+3,j+3]
        if mult>max: max = mult
                
for i in range(3,20):
    for j in range(16): 
        mult =  grid[i,j]*grid[i-1,j+1]*grid[i-2,j+2]*grid[i-3,j+3]
        if mult>max:max = mult
return max
            

70600674


In [14]:
import numpy as np

def grid_max():
grid = np.load("grid.npy")
    horizontal = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    vertical = np.max(grid.T[:,:-3] * grid.T[:,1:-2] * grid.T[:,2:-1] * grid.T[:,3:])
    diagmain = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    diag_rev = np.max(grid[3:,:-3] * grid[2:-1,1:-2] * grid[1:-2,2:-1] * grid[:-3,3:])
    
    return max(horizontal,vertical,diagmain,diag_rev)

grid_max()

70600674